# 使用yaml做配置项
server:
  bind: "0.0.0.0"
  port: 9000
  mode: debug
  cors:
    origins: ["*"]
    methods: ["PUT", "PATCH", "POST", "GET", "DELETE"]
# 数据库配置项
db:
  type: sqlite # mysql or sqlite
  mysql:
    dbname: "example"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"
  sqlite:
    filePath: ./test.db
log:
  # 默认路径是运行程序的目录
  #  path: ./logging
  infoFilename: info.log
  errorFilename: error.log
  maxSize: 10
  maxBackups: 5
  maxAge: 10
  level: info
# 文件上传配置
upload:
  upload_dir: "./uploads"
  temp_dir: "./uploads/temp"
  max_file_size: 10737418240  # 10GB
  chunk_size: 5242880  # 5MB
  allowed_types: "*"  # 允许所有类型，也可以设置为 "image/jpeg,image/png,application/pdf" 等
  cleanup_expiry: 24  # 24小时后清理未完成的上传